### PR TITLE
fix: replace md5

### PR DESCRIPTION
**Pull request by Julusian**
the builtin crypto module supports generating md5 hashes, you dont need a npm library to do it in nodejs (you might for clientside still)

### CODE REVIEW

**Comment by JeffreyDavidsz** [comment]
Without `const crypto = require('crypto')` I'm not able to get the crypto part working. Should we add it to module-base for consistency?

**Comment by Julusian** [comment]
Oops, yeah I meant to include that line, but it slipped through..

Add it to module-base where? Do we need it there?

**Comment by JeffreyDavidsz** [comment]
Well it might be a idea if people use the module-base as the generic helper for all included dependencies? maybe a module-dep next to module-base and module-tools?

**Comment by Julusian** [comment]
How does adding it to module-base help?

There isn't an npm dependency being used, so unless you want to expose a `md5()` function from module-base I dont think there is anything to put there.

**Comment by JeffreyDavidsz** [comment]
Yeah that

**Pull request merged**
